Server: "127.0.0.1:8080"
Env: "product"
Debug: false
RunMode: release
Component:
  Database:
    DriverName: "mysql"
    Addr: "root:123456@(127.0.0.1:3306)/test?charset=utf8mb4"
    MaxOpenConns: 50
    MaxIdleConns: 30
  Redis:
    Addr: "localhost:6379"
    Password: ""
    Database: 0
#  params:
#  如果有新参数可放开注释.自己增加
